# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ltax_basemap_free_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LTaxBasemapFreeDockWidgetBase(object):
    def setupUi(self, LTaxBasemapFreeDockWidgetBase):
        LTaxBasemapFreeDockWidgetBase.setObjectName("LTaxBasemapFreeDockWidgetBase")
        LTaxBasemapFreeDockWidgetBase.resize(298, 190)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(280, 150))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 46, 13))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setIconSize(QtCore.QSize(24, 24))
        self.comboBox.setObjectName("comboBox")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/ic_launcher.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon, "")
        self.comboBox.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/google_map_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon1, "")
        self.comboBox.addItem(icon1, "")
        self.comboBox.addItem(icon1, "")
        self.comboBox.addItem(icon1, "")
        self.comboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/gistda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/ldd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon3, "")
        self.comboBox.addItem(icon3, "")
        self.comboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/stamen_terrain.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/Stamen_toner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/map15.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/wikimedia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon7, "")
        self.comboBox.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/esri3.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon8, "")
        self.comboBox.addItem(icon8, "")
        self.comboBox.addItem(icon8, "")
        self.comboBox.addItem(icon8, "")
        self.comboBox.addItem(icon8, "")
        self.comboBox.addItem(icon8, "")
        self.comboBox.addItem(icon8, "")
        self.comboBox.addItem(icon8, "")
        self.comboBox.addItem(icon8, "")
        self.comboBox.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/osm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon9, "")
        self.comboBox.addItem(icon9, "")
        self.comboBox.addItem(icon9, "")
        self.comboBox.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/strava.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon10, "")
        self.comboBox.addItem(icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/openwheatermap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon11, "")
        self.comboBox.addItem(icon11, "")
        self.comboBox.addItem(icon11, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/cartodb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon12, "")
        self.comboBox.addItem(icon12, "")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/plugins/ltax_basemap_free/icons/bing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon13, "")
        self.btnLoad = QtWidgets.QPushButton(self.tab)
        self.btnLoad.setGeometry(QtCore.QRect(10, 70, 241, 31))
        self.btnLoad.setObjectName("btnLoad")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 251, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 211, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        LTaxBasemapFreeDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(LTaxBasemapFreeDockWidgetBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LTaxBasemapFreeDockWidgetBase)

    def retranslateUi(self, LTaxBasemapFreeDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        LTaxBasemapFreeDockWidgetBase.setWindowTitle(_translate("LTaxBasemapFreeDockWidgetBase", "LTax Basemap Free."))
        self.label.setText(_translate("LTaxBasemapFreeDockWidgetBase", "Basemap :"))
        self.comboBox.setItemText(0, _translate("LTaxBasemapFreeDockWidgetBase", "รูปแปลงกรมที่ดิน (1)"))
        self.comboBox.setItemText(1, _translate("LTaxBasemapFreeDockWidgetBase", "รูปแปลงกรมที่ดิน (2)"))
        self.comboBox.setItemText(2, _translate("LTaxBasemapFreeDockWidgetBase", "Google Maps"))
        self.comboBox.setItemText(3, _translate("LTaxBasemapFreeDockWidgetBase", "Google Satellite"))
        self.comboBox.setItemText(4, _translate("LTaxBasemapFreeDockWidgetBase", "Google Hybrid"))
        self.comboBox.setItemText(5, _translate("LTaxBasemapFreeDockWidgetBase", "Google Hybrid Traffic"))
        self.comboBox.setItemText(6, _translate("LTaxBasemapFreeDockWidgetBase", "Google Terrain Hybrid"))
        self.comboBox.setItemText(7, _translate("LTaxBasemapFreeDockWidgetBase", "L02_base_mo_Thailand_GISTDA_2m"))
        self.comboBox.setItemText(8, _translate("LTaxBasemapFreeDockWidgetBase", "LDD RASTER"))
        self.comboBox.setItemText(9, _translate("LTaxBasemapFreeDockWidgetBase", "LDD Landuse"))
        self.comboBox.setItemText(10, _translate("LTaxBasemapFreeDockWidgetBase", "LDD Orthophoto 2545"))
        self.comboBox.setItemText(11, _translate("LTaxBasemapFreeDockWidgetBase", "Stamen Terrain"))
        self.comboBox.setItemText(12, _translate("LTaxBasemapFreeDockWidgetBase", "Stamen Toner"))
        self.comboBox.setItemText(13, _translate("LTaxBasemapFreeDockWidgetBase", "Stamen Watercolor"))
        self.comboBox.setItemText(14, _translate("LTaxBasemapFreeDockWidgetBase", "Wikimedia Map"))
        self.comboBox.setItemText(15, _translate("LTaxBasemapFreeDockWidgetBase", "Wikimedia Hike Bike Map"))
        self.comboBox.setItemText(16, _translate("LTaxBasemapFreeDockWidgetBase", "Esri Boundaries Places"))
        self.comboBox.setItemText(17, _translate("LTaxBasemapFreeDockWidgetBase", "Esri Gray (dark)"))
        self.comboBox.setItemText(18, _translate("LTaxBasemapFreeDockWidgetBase", "Esri Gray (light)"))
        self.comboBox.setItemText(19, _translate("LTaxBasemapFreeDockWidgetBase", "Esri National Geographic"))
        self.comboBox.setItemText(20, _translate("LTaxBasemapFreeDockWidgetBase", "Esri Ocean"))
        self.comboBox.setItemText(21, _translate("LTaxBasemapFreeDockWidgetBase", "Esri Satellite"))
        self.comboBox.setItemText(22, _translate("LTaxBasemapFreeDockWidgetBase", "Esri Standard"))
        self.comboBox.setItemText(23, _translate("LTaxBasemapFreeDockWidgetBase", "Esri Terrain"))
        self.comboBox.setItemText(24, _translate("LTaxBasemapFreeDockWidgetBase", "Esri Transportation"))
        self.comboBox.setItemText(25, _translate("LTaxBasemapFreeDockWidgetBase", "Esri Topo World"))
        self.comboBox.setItemText(26, _translate("LTaxBasemapFreeDockWidgetBase", "OpenStreetMap Standard"))
        self.comboBox.setItemText(27, _translate("LTaxBasemapFreeDockWidgetBase", "OpenStreetMap H.O.T."))
        self.comboBox.setItemText(28, _translate("LTaxBasemapFreeDockWidgetBase", "OpenStreetMap Monochrome"))
        self.comboBox.setItemText(29, _translate("LTaxBasemapFreeDockWidgetBase", "OpenTopoMap"))
        self.comboBox.setItemText(30, _translate("LTaxBasemapFreeDockWidgetBase", "Strava All"))
        self.comboBox.setItemText(31, _translate("LTaxBasemapFreeDockWidgetBase", "Strava Run"))
        self.comboBox.setItemText(32, _translate("LTaxBasemapFreeDockWidgetBase", "Open Weather Map Temperature"))
        self.comboBox.setItemText(33, _translate("LTaxBasemapFreeDockWidgetBase", "Open Weather Map Clouds"))
        self.comboBox.setItemText(34, _translate("LTaxBasemapFreeDockWidgetBase", "Open Weather Map Wid Speed"))
        self.comboBox.setItemText(35, _translate("LTaxBasemapFreeDockWidgetBase", "CartoDb Dark Matter"))
        self.comboBox.setItemText(36, _translate("LTaxBasemapFreeDockWidgetBase", "CartoDb Positron"))
        self.comboBox.setItemText(37, _translate("LTaxBasemapFreeDockWidgetBase", "Bing VirtualEarth"))
        self.btnLoad.setText(_translate("LTaxBasemapFreeDockWidgetBase", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("LTaxBasemapFreeDockWidgetBase", "LTax Basemap free.(20220814)"))
        self.label_2.setText(_translate("LTaxBasemapFreeDockWidgetBase", "<html><head/><body><p><a href=\'http://www.thaisarabun.com/gistool/\'>LTax BaseMap Free.</a></p></body></html>"))
        self.label_3.setText(_translate("LTaxBasemapFreeDockWidgetBase", "by Attagorn Srinarong (TongzGIS)"))
        self.label_4.setText(_translate("LTaxBasemapFreeDockWidgetBase", "Line ID: attagorn, Mobile: 085-4885780"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("LTaxBasemapFreeDockWidgetBase", "About"))

from .resources import *

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LTaxBasemapFreeDockWidgetBase = QtWidgets.QDockWidget()
    ui = Ui_LTaxBasemapFreeDockWidgetBase()
    ui.setupUi(LTaxBasemapFreeDockWidgetBase)
    LTaxBasemapFreeDockWidgetBase.show()
    sys.exit(app.exec_())

